# Makefile

PLASMOID_PLUGIN_NAME := $$(grep "X-KDE-PluginInfo-Name" $(PWD)/plasmoid/metadata.desktop | cut -d'=' -f2)
PLASMOID_PLUGIN_VERSION := $$(grep "X-KDE-PluginInfo-Version" $(PWD)/plasmoid/metadata.desktop | cut -d'=' -f2)
PACKAGE_FILE := $(PWD)/$(PLASMOID_PLUGIN_NAME)--v$(PLASMOID_PLUGIN_VERSION).plasmoid

all:
	find plasmoid/ \( -name *.qmlc -o -name *.jsc \) -exec rm -f "{}" \; && \
	cd plasmoid && \
	zip -r $(PACKAGE_FILE) *
	@echo Built $(PACKAGE_FILE)
